In [2]:
import numpy as np

In [7]:
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
index=np.where((a>=5)&(a<14))
a[index]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [9]:
a[(a>=5)&(a<14)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [10]:
a[(a%2==0)]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [11]:
index=np.where((a%2==0))
a[index]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [15]:
x=[]
for i in range(0,6):
    z=int(input("enter: "))
    x.append(z)
w=np.array(x)
print(w)

ValueError: invalid literal for int() with base 10: ''

In [4]:
url='iris.data'
iris=np.genfromtxt(url,delimiter=',',dtype='object')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [17]:
names=('sepalLength','sepalwidth','petalLength','petalWidth','species')

In [5]:
sepalLength=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[2])
med=np.median(sepalLength)
print(med)

4.35


In [6]:
mean,sd=np.mean(sepalLength),np.std(sepalLength)
print(mean,sd)

3.758666666666666 1.7585291834055212
