In [2]:
import numpy as np

In [6]:
array=np.random.random((3,3,3))
array

array([[[0.36254716, 0.66292345, 0.96630428],
        [0.4124466 , 0.31093325, 0.73891854],
        [0.42178686, 0.67745753, 0.96277968]],

       [[0.42853534, 0.21489316, 0.37726832],
        [0.73772617, 0.96142303, 0.94054299],
        [0.34619849, 0.49375056, 0.07616558]],

       [[0.72561027, 0.19867782, 0.02340019],
        [0.38849019, 0.55049766, 0.19639335],
        [0.6512662 , 0.15050452, 0.10854182]]])

In [7]:
arr=np.random.random((5,5))


In [8]:
arr

array([[0.49706951, 0.65946141, 0.1936971 , 0.88317153, 0.3591529 ],
       [0.43452055, 0.89271492, 0.33408185, 0.22085638, 0.51460658],
       [0.18785001, 0.39781113, 0.07173265, 0.8993177 , 0.82940755],
       [0.64910751, 0.10315875, 0.06209804, 0.53454698, 0.54668366],
       [0.78229598, 0.11561314, 0.85872635, 0.20138561, 0.51566165]])

In [9]:
print(np.min(arr))
print(np.max(arr))

0.06209804401822372
0.8993176955365904


In [10]:
arr2=np.random.random((10,4))
arr2

array([[0.67954332, 0.78450957, 0.05050293, 0.87516061],
       [0.42919238, 0.25357917, 0.67733499, 0.39238615],
       [0.98148168, 0.4844884 , 0.42157889, 0.49752876],
       [0.38004775, 0.05363152, 0.65850239, 0.39640362],
       [0.4495792 , 0.18329969, 0.14288376, 0.06344887],
       [0.8121002 , 0.14498703, 0.69344883, 0.49567569],
       [0.10348863, 0.20868383, 0.88915531, 0.11177207],
       [0.04190824, 0.03136843, 0.94577403, 0.73936513],
       [0.27714013, 0.32217622, 0.30218733, 0.58657723],
       [0.70409154, 0.60323126, 0.53692588, 0.30169916]])

In [11]:
arr3=arr2[0:4]

In [12]:
arr3

array([[0.67954332, 0.78450957, 0.05050293, 0.87516061],
       [0.42919238, 0.25357917, 0.67733499, 0.39238615],
       [0.98148168, 0.4844884 , 0.42157889, 0.49752876],
       [0.38004775, 0.05363152, 0.65850239, 0.39640362]])

In [15]:
array11= np.array([1.2, 2.4, 3.6, 4.8, 6.0])
given_val=3.1
ab=np.abs(array11-given_val)
index=np.argmin(ab)
print(array11[index])

3.6


In [16]:
ra=np.arange(9)
ra

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
ra.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])